# baseurl to be set depending on the env.
# baseurl = ""
languageCode = "en-us"
title = "Riadh Habbachi's Blog"
theme = "hugo-cactus-theme"
MetaDataFormat = "toml"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-102080280-1"

# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
name = "Riadh Habbachi"
description = "Describe your website"
bio = "Software Craftsman, Technology enthusiast."

# Enter optionally your twitter account
twitter = ""
enableRSS = true

# Add custom assets with their paths relative to the static folder
customCSS = []
customJS  = []

# The variables below are optionally too and can be used to
# translate or customize each string of the theme.

# Navigation links
home = "/home"
about = "/about"
subscribe = "/feed"
resume = "/resume"

# Pagination links
olderPosts = ""
newerPosts = ""
readMore = ""
copyright = ""

# Sharing options and author information in posts
aboutAuthor = ""
tweet = ""
share = ""

# 404 page
title404 = "OOPS!"
subtitle404 = "There is a chance that what you typed is wrong, but most likely I broke something. Sorry!"

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "mono-social"
# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
socialIconStyle = "circle"

# Use gavatar as author image.
gravatarHash = "57071062dd66187743d31ab6985565b4"

# Add additional social link entries underneath
[social]
githubalt = "https://www.github.com/rhabbachi"
drupal = "https://www.drupal.org/u/rhabbachi"
linkedin = "https://www.linkedin.com/in/rhabbachi"
rss = "/index.xml"

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
post = "/:year/:month/:day/:title/" # optional
