version: "2.1"

services:
  cli:
    extends:
      file: ${PROJECT_ROOT}/.docksal/docksal-local.yml
      service: cli

  web:
    extends:
      file: ${PROJECT_ROOT}/.docksal/docksal-local.yml
      service: web
    labels:
      # Traefik
      traefik.enable: true
      traefik.port: 80
      traefik.backend: ${COMPOSE_PROJECT_NAME_SAFE}-web
      traefik.frontend.rule: Host:${VIRTUAL_HOST}
    environment:
      - NGINX_BASIC_AUTH_USER
      - NGINX_BASIC_AUTH_PASS
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  crontab:
    image: willfarrell/crontab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
        # TODO add config from ./etc.
    logging:
      driver: json-file
      options:
        # Limit log size
        max-size: "200k"
        max-file: "10"
